# BEGIN
spring:
  h2:
    console:
      enabled: true
  datasource:
    password: admin
    url: "jdbc:h2:mem:project"
    #url: "jdbc:h2:/data/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090"
    username: admin
  config:
    activate:
      on-profile: development
# END
