# BEGIN
spring:
  h2:
    console:
      enabled: true
  datasource:
    password: admin
    #url: "jdbc:h2:file:./test"
    #url: "jdbc:h2:/data/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090"
    url: "jdbc:h2:/data/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090"
    #url: "jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
    username: admin
  config:
    activate:
      on-profile: development
# END
